server:
    port: 8085
directory:
    mount: /mnt/SAN
spring:
    freemarker:
        cache: false
        charset: UTF-8
        suffix: .html
        template-loader-path: 'classpath:/templates/ '
    mvc:
        static-path-pattern: /static/**
        view:
            suffix: .html
